import type { Metadata } from "next";
import "./globals.css";
import UIProvider from "@/components/NextUIProvider";
import { Inter } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  weight: "variable",
});

export const metadata: Metadata = {
  title: "Administration",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={"bg-neutral-100"}>
        <UIProvider>{children}</UIProvider>
      </body>
    </html>
  );
}
