import type {Metadata} from "next";
import "./globals.css";
import UIProvider from "@/components/NextUIProvider";
import {Inter} from "next/font/google";
import {ReactNode} from "react";
import {getKindeServerSession} from "@kinde-oss/kinde-auth-nextjs/server";
import Auth from "@/components/auth";
import {KindeProvider} from "@kinde-oss/kinde-auth-nextjs";
import {ViewProvider} from "@/context/view";
import {redirect} from "next/navigation";

const inter = Inter({
    subsets: ["latin"],
    weight: "variable",
});

export const metadata: Metadata = {
    title: "Administration",
    description: "Generated by create next app",
};

export default async function RootLayout({
                                             children,
                                         }: Readonly<{
    children: ReactNode;
}>) {
    const {isAuthenticated} = getKindeServerSession();

    if (!await isAuthenticated()) {
        redirect('/api/auth/login');
        return <html></html>;
    }
    return (
        <html lang="en">
        <body className={`${inter.className} w-full h-max bg-neutral-100`}>
        <UIProvider>
            <ViewProvider>
                {children}
            </ViewProvider>
        </UIProvider>
        </body>
        </html>
    );
}
