import type { Metadata } from "next";
import "./globals.css";
import UIProvider from "@/components/NextUIProvider";
import { Inter } from "next/font/google";
import { ViewProvider } from "@/context/view";
import { ReactNode } from "react";
import Nav from "@/components/nav";

const inter = Inter({
  subsets: ["latin"],
  weight: "variable",
});

export const metadata: Metadata = {
  title: "Administration",
  description: "Generated by create next app",
};

export default function RootLayout({
  dashboard,
  yachts,
}: Readonly<{
  dashboard: ReactNode;
  yachts: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} w-full h-max bg-neutral-100`}>
        <UIProvider>
          <ViewProvider dashboard={dashboard} yachts={yachts}>
            <Nav />
          </ViewProvider>
        </UIProvider>
      </body>
    </html>
  );
}
